Feature/map widget
MusicConnectionMachine/VisualizationG6 pull request #45
Opened 2017-03-26 22:28 UTC by ysdevys

I suggest a merge at this stage because of the new dependencies and to avoid further complications with a later merge.

2017-03-27 08:42 UTC, demirdagemir requested changes
Please move the image inside `/style/img`, that's where we keep the images. You could then update the image link where you use it. The location pin image doesn't show up on the map component. (Image not found)

2017-03-27 08:42 UTC, demirdagemir commented on README.md
> +### MapView widget
I think you could either delete this or adjust it accordingly: The readme file we use it to explain functionalities for people -outside- who could use the source code, not to report our current status to our teammates.

2017-03-27 08:42 UTC, demirdagemir commented on index.html
> +    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
We already have this in the dependencies. Please move these to the related component. (MapView.js)
You don't have to use a CDN, you could just do, inside MapView, `import 'leaflet/dist/leaflet.css'`

2017-03-27 08:55 UTC, demirdagemir requested changes

2017-03-27 08:55 UTC, demirdagemir commented on package.json
> +    "leaflet": "^1.0.3",
I'm not sure about this, I would like to ask the tutors, when should we use dependencies or devDependencies? I always get confused: I'm guessing webpack will bundle only dependencies inside a production environment, but we generally install only what we need. Don't we need every dependency? Except maybe webpack-dev-server. @kordianbruck @sacdallago

2017-03-27 09:01 UTC, demirdagemir commented on style/mapview.scss
> +	margin: 20px;
Could you also fix the indentation here, please?

2017-03-27 18:52 UTC, kordianbruck commented on package.json
> +    "leaflet": "^1.0.3",
Let me quote this:
```
dependencies are required to run, devDependencies only to develop, e.g.: unit tests, Coffeescript to Javascript transpilation, minification, ...
```
https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

2017-03-27 18:54 UTC, kordianbruck commented
Fixes issue #42

2017-04-04 08:40 UTC, ysdevys commented on style/mapview.scss
> +	margin: 20px;
done

2017-04-04 08:41 UTC, ysdevys commented on index.html
> +    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
thanks

2017-04-04 08:41 UTC, ysdevys commented on README.md
> +### MapView widget
done

2017-04-05 12:01 UTC, demirdagemir approved these changes

2017-04-08 10:57 UTC, demirdagemir commented
@ysdevys Can you please merge this?

2017-04-09 18:54 UTC, merged